### ISSUE TITLE
multiprocessing.pool.RemoteTraceback

### ISSUE THREAD

**Issue by sunhaifeng123** [MasaakiU/MultiplexNanopore#6]
Hi MasaakiU,
I created a conda virtual environment and installed MultiplexNanopore by pip on ubuntu. It seems that erverthing is OK to run several days. But today a running gives an error:

python -m savemoney.post_analysis -nc 16 in1/ ./
n_cpu=16 (max=16)
executing alignment...
 30%|█████████████████▋                                          | 646/2186 [00:24<00:58, 26.16it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/kelab/miniconda3/envs/save/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/kelab/miniconda3/envs/save/lib/python3.10/site-packages/savemoney/post_analysis/post_analysis_core.py", line 67, in execute_alignment_core_loop_wrapper
    return execute_alignment_core_loop(*args)
  File "/home/kelab/miniconda3/envs/save/lib/python3.10/site-packages/savemoney/post_analysis/post_analysis_core.py", line 77, in execute_alignment_core_loop
    my_result = my_optimized_aligner.execute_alignment_using_conserved_regions(query_seq, conserved_regions)
  File "/home/kelab/miniconda3/envs/save/lib/python3.10/site-packages/savemoney/modules/ref_query_alignment.py", line 221, in execute_alignment_using_conserved_regions
    return self.execute_alignment_using_conserved_regions_circular(query_seq, conserved_regions)
  File "/home/kelab/miniconda3/envs/save/lib/python3.10/site-packages/savemoney/modules/ref_query_alignment.py", line 316, in execute_alignment_using_conserved_regions_circular
    self.assert_alignment(self.ref_seq, query_seq, result_master.my_cigar)
  File "/home/kelab/miniconda3/envs/save/lib/python3.10/site-packages/savemoney/modules/my_classes.py", line 415, in assert_alignment
    assert ref_seq[r_idx] != query_seq[q_idx]
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kelab/miniconda3/envs/save/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/kelab/miniconda3/envs/save/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/kelab/miniconda3/envs/save/lib/python3.10/site-packages/savemoney/post_analysis/__main__.py", line 34, in <module>
    post_analysis(args.sequence_dir_paths, args.save_dir_base, **param_dict)
  File "/home/kelab/miniconda3/envs/save/lib/python3.10/site-packages/savemoney/post_analysis/post_analysis.py", line 31, in post_analysis
    return post_analysis_separate_paths_input(plasmid_map_paths, fastq_paths, save_dir_base, **param_dict)
  File "/home/kelab/miniconda3/envs/save/lib/python3.10/site-packages/savemoney/post_analysis/post_analysis.py", line 49, in post_analysis_separate_paths_input
    result_dict, ref_seq_list = pac.execute_alignment(ref_seq_list, my_fastq, param_dict, save_dir)
  File "/home/kelab/miniconda3/envs/save/lib/python3.10/site-packages/savemoney/post_analysis/post_analysis_core.py", line 46, in execute_alignment
    result_dict = execute_alignment_core(ref_seq_list, my_fastq, param_dict)
  File "/home/kelab/miniconda3/envs/save/lib/python3.10/site-packages/savemoney/post_analysis/post_analysis_core.py", line 61, in execute_alignment_core
    result_list_list = list(tqdm(p.imap(execute_alignment_core_loop_wrapper, input_iter), ncols=100, mininterval=0.1, leave=True, bar_format='{l_bar}{bar}{r_bar}', total=len(my_fastq)))
  File "/home/kelab/miniconda3/envs/save/lib/python3.10/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/home/kelab/miniconda3/envs/save/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
AssertionError

I try to figure it out but failed. Despite, I think it's the fastq problems because I choose some fastq using head/tail can be analysed successfully, but some can not. I attached the tar.gz file to you and looking for you help!

Thanks in advance!
[in.tar.gz](https://github.com/user-attachments/files/16698686/in.tar.gz)

Haifeng Sun

**Comment by sunhaifeng123** [comment]
and also the conda environment: 
[save.conda.environment.yml.tar.gz](https://github.com/user-attachments/files/16698725/save.conda.environment.yml.tar.gz)
Thanks!

**Comment by MasaakiU** [comment]
Thank you for the bug report.
The bug was on SAVEMONEY side, and was fixed in ver_0.3.4.

One of your reads showed an exact match against Assemble2.dna for more than one round, so the start and end of the match was recognized incorrectly.
Please try to see if the new version runs well, and let me know if you have any question.

**Comment by sunhaifeng123** [comment]
It works after I upgraded MultiplexNanopore to the newest version! Thank you so much, Masaaki!

**Comment by MasaakiU** [comment]
Awesome!
It's my pleasure!
